#!/bin/bash

HERACLES_LC_PID=9999

HERACLES_LATENCY_FILE=
HERACLES_MAX_LATENCY_FILE=
HERACLES_LOAD_FILE=
HERACLES_MAX_LOAD_FILE=

HERACLES_DRAM_LIMIT=1024

CORE_MEMORY_SLEEP_TIME=2

TOP_SLEEP_TIME=5
TOP_DISABLE_BOND=0.85
TOP_ENABLE_BOUND=0.8
TOP_SLOW_BE_BOUND=0.1

CGROUPS_DIR=/sys/fs/cgroups
# default for Linux ubuntu

HERACLES_IDLE_NUM=1
